_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('school.urls', namespace='school')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()

school/urls.py
# school/urls.py

from django.urls import path
from school import views

app_name = 'school'

urlpatterns = [
    path('', views.index, name='index'),
    path('students/', views.students, name='students'),
    # path('courses/', views.courses, name='courses'),
    path('courses/', views.CourseList.as_view(), name='courses'),
    # path('courses/<int:pk>/', views.course_detail, name='course_detail'),
    path('courses/<int:pk>/', views.CourseDetail.as_view(), name='course_detail'),
]

school/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Course(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(max_length=1000, blank=True)
    # /media/course/...¨
    # blank = volené na úrovní UI
    # null =  volené na úrovní DB
    image = models.ImageField(blank=True, null=True, upload_to='course/')

    # vazba 1:N na User - Course.user_id -> User.id
    # on_delete co se má stát se záznamy Course, pokud vymažeme User
    # v tomto případě se nastaví null pokud uživatele vymažeme
    lector = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name='lector_courses')

    # vazba M:N na User, blank - není povinné aby tam měl studenty
    students = models.ManyToManyField(User, blank=True, related_name='student_courses')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        # path('courses/<int:pk>/', name='course_detail')
        # /courses/1/
        return reverse('school:course_detail', kwargs={"pk": self.pk})
    

school/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.views import generic
from school import models

# views.py

def index(request):
    return render(request, 'school/index.html')

def students(request):
    return render(request, 'school/students.html')

def courses(request):
    courses = models.Course.objects.all()
    return render(
        request,
        'school/courses.html',
        {'courses': courses}
    )

# /courses/10/

def course_detail(request, pk):
    course = get_object_or_404(models.Course, id=pk)
    return render(request, 'school/course_detail.html', {'course': course})


class CourseDetail(generic.DetailView):
    model = models.Course


class CourseList(generic.ListView):
    # school/course_list.html
    # model = models.Course
    # custom queryset + select related pro optimalizaci napojených záznamů
    queryset  = models.Course.objects.select_related('lector')
    template_name = 'school/courses.html'
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator'] # stará se o stránkování 
        page_obj = context['page_obj'] # objekt reprezentující aktuální stránku
        context['paginator_range'] = paginator.get_elided_page_range(
            page_obj.number,
            on_each_side=1,
            on_ends=1,
        )
        return context

school/templates/school/_base.html
<!doctype html>
<html lang="en">{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark" >
    <link rel="stylesheet" href="{% static 'school/pico.min.css' %}">
    <link rel="stylesheet" href="{% static 'school/main.css' %}?v=1">
    <title>{% block school_title %}{% endblock %}</title>
    <meta name="description" content="{% block school_desc %}{% endblock %}">
  </head>
  <body>
    <main class="container">
      <nav>
        <ul>
          <li><a href="{% url 'school:index' %}">Home</a></li>
          <li><a href="{% url 'school:courses' %}">Courses</a></li>
          <li><a href="{% url 'school:students' %}">Students</a></li>
        </ul>
      </nav>

      {% block school_base %}{% endblock %}
    </main>
  </body>
</html>

school/templates/school/course_detail.html
{% extends "school/_base.html" %}

{% block school_title %}{{ course.name }}{% endblock %}
{% block school_desc %}{% endblock %}

{% block school_base %}
    <h1>{{ course.name }}</h1>
{% endblock %}

school/templates/school/courses.html
{% extends "school/_base.html" %}

{% block school_title %}Courses{% endblock %}
{% block school_desc %}Courses of School App, for IT School in Prague.{% endblock %}

{% block school_base %}
    <h1>Courses</h1>

    <ul class="list">
        {% for course in object_list %}
        <li>
            {# hello ... #}

            {% comment %}
            {% url 'school:course_detail' pk=course.id %}
            {% endcomment %}
            <a href="{{ course.get_absolute_url }}">
                {% if course.image %}
                <img src="{{ course.image.url }}" alt="" loading="lazy">
                {% else %}
                <img src="https://picsum.photos/100" alt="" loading="lazy">
                {% endif %}
                <h2>{{ course.name }} - {{ course.lector.username }}</h2>
            </a>
        </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav>
            <ul>
                {% for number in paginator_range %}
                    <li>
                        {% if number != paginator.ELLIPSIS %}
                        <a href="{{ request.path }}?page={{ number }}">{{ number }}</a>
                        {% else %}
                        {{ number }}
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

school/templates/school/index.html
{% extends "school/_base.html" %}

{% block school_title %}School App{% endblock %}
{% block school_desc %}This School App, for IT School in Prague.{% endblock %}

{% block school_base %}
    <h1>Index</h1>
{% endblock %}

school/templates/school/students.html
{% extends "school/_base.html" %}

{% block school_title %}Students{% endblock %}
{% block school_desc %}Students of School App, for IT School in Prague.{% endblock %}

{% block school_base %}
    <h1>Students</h1>
{% endblock %}